// Code generated by protoc-gen-go. DO NOT EDIT.
// source: country.proto

package iso // import "github.com/nycmonkey/iso"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ISO Country codes, plus a couple of FactSet additions
type Country int32

const (
	Country_UNKNOWN_COUNTRY Country = 0
	// Supranational
	Country_SUPRANATIONAL Country = 1
	// N/A
	Country_NOT_APPLICABLE Country = 2
	// Andorra
	Country_AD Country = 3
	// United Arab Emirates
	Country_AE Country = 4
	// Afghanistan
	Country_AF Country = 5
	// Antigua and Barbuda
	Country_AG Country = 6
	// Anguilla
	Country_AI Country = 7
	// Albania
	Country_AL Country = 8
	// Armenia
	Country_AM Country = 9
	// Netherlands Antilles
	Country_AN Country = 10
	// Angola
	Country_AO Country = 11
	// Asia Pacific Region
	Country_AP Country = 12
	// Antarctica
	Country_AQ Country = 13
	// Argentina
	Country_AR Country = 14
	// American Samoa
	Country_AS Country = 15
	// Austria
	Country_AT Country = 16
	// Australia
	Country_AU Country = 17
	// Aruba
	Country_AW Country = 18
	// Aland Islands
	Country_AX Country = 19
	// Azerbaijan
	Country_AZ Country = 20
	// Bosnia and Herzegovina
	Country_BA Country = 21
	// Barbados
	Country_BB Country = 22
	// Bangladesh
	Country_BD Country = 23
	// Belgium
	Country_BE Country = 24
	// Burkina Faso
	Country_BF Country = 25
	// Bulgaria
	Country_BG Country = 26
	// Bahrain
	Country_BH Country = 27
	// Burundi
	Country_BI Country = 28
	// Benin
	Country_BJ Country = 29
	// Saint Barthelemy
	Country_BL Country = 30
	// Bermuda
	Country_BM Country = 31
	// Brunei
	Country_BN Country = 32
	// Bolivia
	Country_BO Country = 33
	// Bonaire, St. Eust., Saba
	Country_BQ Country = 34
	// Brazil
	Country_BR Country = 35
	// Bahamas
	Country_BS Country = 36
	// Bhutan
	Country_BT Country = 37
	// Bouvet Island
	Country_BV Country = 38
	// Botswana
	Country_BW Country = 39
	// Belarus
	Country_BY Country = 40
	// Belize
	Country_BZ Country = 41
	// Canada
	Country_CA Country = 42
	// Cocos (Keeling) Islands
	Country_CC Country = 43
	// Congo (Dem. Rep. of the)
	Country_CD Country = 44
	// Central African Republic
	Country_CF Country = 45
	// Congo (Rep. of)
	Country_CG Country = 46
	// Switzerland
	Country_CH Country = 47
	// Ivory Coast
	Country_CI Country = 48
	// Cook Islands
	Country_CK Country = 49
	// Chile
	Country_CL Country = 50
	// Cameroon
	Country_CM Country = 51
	// China
	Country_CN Country = 52
	// Colombia
	Country_CO Country = 53
	// Costa Rica
	Country_CR Country = 54
	// Serbia & Montenegro
	Country_CS Country = 55
	// Cuba
	Country_CU Country = 56
	// Cape Verde
	Country_CV Country = 57
	// Curacao
	Country_CW Country = 58
	// Christmas Island
	Country_CX Country = 59
	// Cyprus
	Country_CY Country = 60
	// Czech Republic
	Country_CZ Country = 61
	// East Germany
	Country_DD Country = 62
	// Germany
	Country_DE Country = 63
	// Djibouti
	Country_DJ Country = 64
	// Denmark
	Country_DK Country = 65
	// Dominica
	Country_DM Country = 66
	// Dominican Republic
	Country_DO Country = 67
	// Algeria
	Country_DZ Country = 68
	// Ecuador
	Country_EC Country = 69
	// Estonia
	Country_EE Country = 70
	// Egypt
	Country_EG Country = 71
	// Western Sahara
	Country_EH Country = 72
	// Eritrea
	Country_ER Country = 73
	// Spain
	Country_ES Country = 74
	// Ethiopia
	Country_ET Country = 75
	// Europe Region
	Country_EU Country = 76
	// Finland
	Country_FI Country = 77
	// Fiji
	Country_FJ Country = 78
	// Falkland Islands
	Country_FK Country = 79
	// Micronesia
	Country_FM Country = 80
	// Faroe Islands
	Country_FO Country = 81
	// France
	Country_FR Country = 82
	// Gabon
	Country_GA Country = 83
	// United Kingdom
	Country_GB Country = 84
	// Grenada
	Country_GD Country = 85
	// Georgia
	Country_GE Country = 86
	// French Guiana
	Country_GF Country = 87
	// Guernsey
	Country_GG Country = 88
	// Ghana
	Country_GH Country = 89
	// Gibraltar
	Country_GI Country = 90
	// Greenland
	Country_GL Country = 91
	// Gambia
	Country_GM Country = 92
	// Guinea
	Country_GN Country = 93
	// Guadeloupe
	Country_GP Country = 94
	// Equatorial Guinea
	Country_GQ Country = 95
	// Greece
	Country_GR Country = 96
	// So Georgia & So Sand Isl
	Country_GS Country = 97
	// Guatemala
	Country_GT Country = 98
	// Guam
	Country_GU Country = 99
	// Guinea-Bissau
	Country_GW Country = 100
	// Guyana
	Country_GY Country = 101
	// Hong Kong
	Country_HK Country = 102
	// Heard & McDonald Islands
	Country_HM Country = 103
	// Honduras
	Country_HN Country = 104
	// Croatia
	Country_HR Country = 105
	// Haiti
	Country_HT Country = 106
	// Hungary
	Country_HU Country = 107
	// Indonesia
	Country_ID Country = 108
	// Ireland
	Country_IE Country = 109
	// Israel
	Country_IL Country = 110
	// Isle of Man
	Country_IM Country = 111
	// India
	Country_IN Country = 112
	// Brit. Indian Ocean Terr.
	Country_IO Country = 113
	// Iraq
	Country_IQ Country = 114
	// Iran
	Country_IR Country = 115
	// Iceland
	Country_IS Country = 116
	// Italy
	Country_IT Country = 117
	// Jersey
	Country_JE Country = 118
	// Jamaica
	Country_JM Country = 119
	// Jordan
	Country_JO Country = 120
	// Japan
	Country_JP Country = 121
	// Kenya
	Country_KE Country = 122
	// Kyrgyzstan
	Country_KG Country = 123
	// Cambodia
	Country_KH Country = 124
	// Kiribati
	Country_KI Country = 125
	// Comoros
	Country_KM Country = 126
	// Saint Kitts and Nevis
	Country_KN Country = 127
	// North Korea
	Country_KP Country = 128
	// South Korea
	Country_KR Country = 129
	// Kuwait
	Country_KW Country = 130
	// Cayman Islands
	Country_KY Country = 131
	// Kazakhstan
	Country_KZ Country = 132
	// Laos
	Country_LA Country = 133
	// Lebanon
	Country_LB Country = 134
	// St. Lucia
	Country_LC Country = 135
	// Liechtenstein
	Country_LI Country = 136
	// Sri Lanka
	Country_LK Country = 137
	// Liberia
	Country_LR Country = 138
	// Lesotho
	Country_LS Country = 139
	// Lithuania
	Country_LT Country = 140
	// Luxembourg
	Country_LU Country = 141
	// Latvia
	Country_LV Country = 142
	// Libya
	Country_LY Country = 143
	// Morocco
	Country_MA Country = 144
	// Monaco
	Country_MC Country = 145
	// Moldova
	Country_MD Country = 146
	// Montenegro
	Country_ME Country = 147
	// Saint Martin
	Country_MF Country = 148
	// Madagascar
	Country_MG Country = 149
	// Marshall Islands
	Country_MH Country = 150
	// Macedonia
	Country_MK Country = 151
	// Mali
	Country_ML Country = 152
	// Myanmar
	Country_MM Country = 153
	// Mongolia
	Country_MN Country = 154
	// Macau
	Country_MO Country = 155
	// Marianas
	Country_MP Country = 156
	// Martinique
	Country_MQ Country = 157
	// Mauritania
	Country_MR Country = 158
	// Montserrat
	Country_MS Country = 159
	// Malta
	Country_MT Country = 160
	// Mauritius
	Country_MU Country = 161
	// Maldives
	Country_MV Country = 162
	// Malawi
	Country_MW Country = 163
	// Mexico
	Country_MX Country = 164
	// Malaysia
	Country_MY Country = 165
	// Mozambique
	Country_MZ Country = 166
	// Namibia
	Country_NA Country = 167
	// New Caledonia
	Country_NC Country = 168
	// Niger
	Country_NE Country = 169
	// Norfolk Island
	Country_NF Country = 170
	// Nigeria
	Country_NG Country = 171
	// Nicaragua
	Country_NI Country = 172
	// Netherlands
	Country_NL Country = 173
	// Norway
	Country_NO Country = 174
	// Nepal
	Country_NP Country = 175
	// Nauru
	Country_NR Country = 176
	// Niue
	Country_NU Country = 177
	// New Zealand
	Country_NZ Country = 178
	// Oman
	Country_OM Country = 179
	// Panama
	Country_PA Country = 180
	// Peru
	Country_PE Country = 181
	// French Polynesia
	Country_PF Country = 182
	// Papua New Guinea
	Country_PG Country = 183
	// Philippines
	Country_PH Country = 184
	// Pakistan
	Country_PK Country = 185
	// Poland
	Country_PL Country = 186
	// Saint Pierre & Miquelon
	Country_PM Country = 187
	// Pitcairn
	Country_PN Country = 188
	// Puerto Rico
	Country_PR Country = 189
	// Palestine
	Country_PS Country = 190
	// Portugal
	Country_PT Country = 191
	// Palau
	Country_PW Country = 192
	// Paraguay
	Country_PY Country = 193
	// Qatar
	Country_QA Country = 194
	// La Reunion
	Country_RE Country = 195
	// Romania
	Country_RO Country = 196
	// Serbia
	Country_RS Country = 197
	// Russian Federation
	Country_RU Country = 198
	// Rwanda
	Country_RW Country = 199
	// Saudi Arabia
	Country_SA Country = 200
	// Solomon Islands
	Country_SB Country = 201
	// Seychelles
	Country_SC Country = 202
	// Sudan
	Country_SD Country = 203
	// Sweden
	Country_SE Country = 204
	// Singapore
	Country_SG Country = 205
	// Saint Helena
	Country_SH Country = 206
	// Slovenia
	Country_SI Country = 207
	// Svalbard and Jan Mayen
	Country_SJ Country = 208
	// Slovakia
	Country_SK Country = 209
	// Sierra Leone
	Country_SL Country = 210
	// San Marino
	Country_SM Country = 211
	// Senegal
	Country_SN Country = 212
	// Somalia
	Country_SO Country = 213
	// Suriname
	Country_SR Country = 214
	// South Sudan
	Country_SS Country = 215
	// Sao Tome and Principe
	Country_ST Country = 216
	// Soviet Union
	Country_SU Country = 217
	// El Salvador
	Country_SV Country = 218
	// Sint Marten
	Country_SX Country = 219
	// Syria
	Country_SY Country = 220
	// Swaziland
	Country_SZ Country = 221
	// Turks and Caicos Islands
	Country_TC Country = 222
	// Chad
	Country_TD Country = 223
	// French Southern Terr.
	Country_TF Country = 224
	// Togo
	Country_TG Country = 225
	// Thailand
	Country_TH Country = 226
	// Tajikistan
	Country_TJ Country = 227
	// Tokelau
	Country_TK Country = 228
	// Timor-Leste
	Country_TL Country = 229
	// Turkmenistan
	Country_TM Country = 230
	// Tunisia
	Country_TN Country = 231
	// Tonga
	Country_TO Country = 232
	// Turkey
	Country_TR Country = 233
	// Trinidad and Tobago
	Country_TT Country = 234
	// Tuvalu
	Country_TV Country = 235
	// Taiwan
	Country_TW Country = 236
	// Tanzania
	Country_TZ Country = 237
	// Ukraine
	Country_UA Country = 238
	// Uganda
	Country_UG Country = 239
	// U.S. Minor Outlying Isl.
	Country_UM Country = 240
	// United States
	Country_US Country = 241
	// Uruguay
	Country_UY Country = 242
	// Uzbekistan
	Country_UZ Country = 243
	// Vatican City
	Country_VA Country = 244
	// St Vincent & Grenadines
	Country_VC Country = 245
	// North Vietnam
	Country_VD Country = 246
	// Venezuela
	Country_VE Country = 247
	// British Virgin Islands
	Country_VG Country = 248
	// U.S. Virgin Islands
	Country_VI Country = 249
	// Vietnam
	Country_VN Country = 250
	// Vanuatu
	Country_VU Country = 251
	// Wallis & Futuna
	Country_WF Country = 252
	// Samoa
	Country_WS Country = 253
	// Kosovo
	Country_XK Country = 254
	// Afr/Mid-East Unallocated
	Country_XP Country = 255
	// Asia/Pacific Unallocated
	Country_XR Country = 256
	// Americas Unallocated
	Country_XS Country = 257
	// Europe Unallocated
	Country_XT Country = 258
	// Zanzibar
	Country_XU Country = 259
	// Tanganyika
	Country_XV Country = 260
	// Non-Geographic Revenue
	Country_XW Country = 261
	// Non-Operating Country
	Country_XY Country = 262
	// Unspecified
	Country_XZ Country = 263
	// South Yemen
	Country_YD Country = 264
	// Yemen
	Country_YE Country = 265
	// Mayotte
	Country_YT Country = 266
	// Yugoslavia
	Country_YU Country = 267
	// South Africa
	Country_ZA Country = 268
	// Zambia
	Country_ZM Country = 269
	// Zimbabwe
	Country_ZW Country = 270
)

var Country_name = map[int32]string{
	0:   "UNKNOWN_COUNTRY",
	1:   "SUPRANATIONAL",
	2:   "NOT_APPLICABLE",
	3:   "AD",
	4:   "AE",
	5:   "AF",
	6:   "AG",
	7:   "AI",
	8:   "AL",
	9:   "AM",
	10:  "AN",
	11:  "AO",
	12:  "AP",
	13:  "AQ",
	14:  "AR",
	15:  "AS",
	16:  "AT",
	17:  "AU",
	18:  "AW",
	19:  "AX",
	20:  "AZ",
	21:  "BA",
	22:  "BB",
	23:  "BD",
	24:  "BE",
	25:  "BF",
	26:  "BG",
	27:  "BH",
	28:  "BI",
	29:  "BJ",
	30:  "BL",
	31:  "BM",
	32:  "BN",
	33:  "BO",
	34:  "BQ",
	35:  "BR",
	36:  "BS",
	37:  "BT",
	38:  "BV",
	39:  "BW",
	40:  "BY",
	41:  "BZ",
	42:  "CA",
	43:  "CC",
	44:  "CD",
	45:  "CF",
	46:  "CG",
	47:  "CH",
	48:  "CI",
	49:  "CK",
	50:  "CL",
	51:  "CM",
	52:  "CN",
	53:  "CO",
	54:  "CR",
	55:  "CS",
	56:  "CU",
	57:  "CV",
	58:  "CW",
	59:  "CX",
	60:  "CY",
	61:  "CZ",
	62:  "DD",
	63:  "DE",
	64:  "DJ",
	65:  "DK",
	66:  "DM",
	67:  "DO",
	68:  "DZ",
	69:  "EC",
	70:  "EE",
	71:  "EG",
	72:  "EH",
	73:  "ER",
	74:  "ES",
	75:  "ET",
	76:  "EU",
	77:  "FI",
	78:  "FJ",
	79:  "FK",
	80:  "FM",
	81:  "FO",
	82:  "FR",
	83:  "GA",
	84:  "GB",
	85:  "GD",
	86:  "GE",
	87:  "GF",
	88:  "GG",
	89:  "GH",
	90:  "GI",
	91:  "GL",
	92:  "GM",
	93:  "GN",
	94:  "GP",
	95:  "GQ",
	96:  "GR",
	97:  "GS",
	98:  "GT",
	99:  "GU",
	100: "GW",
	101: "GY",
	102: "HK",
	103: "HM",
	104: "HN",
	105: "HR",
	106: "HT",
	107: "HU",
	108: "ID",
	109: "IE",
	110: "IL",
	111: "IM",
	112: "IN",
	113: "IO",
	114: "IQ",
	115: "IR",
	116: "IS",
	117: "IT",
	118: "JE",
	119: "JM",
	120: "JO",
	121: "JP",
	122: "KE",
	123: "KG",
	124: "KH",
	125: "KI",
	126: "KM",
	127: "KN",
	128: "KP",
	129: "KR",
	130: "KW",
	131: "KY",
	132: "KZ",
	133: "LA",
	134: "LB",
	135: "LC",
	136: "LI",
	137: "LK",
	138: "LR",
	139: "LS",
	140: "LT",
	141: "LU",
	142: "LV",
	143: "LY",
	144: "MA",
	145: "MC",
	146: "MD",
	147: "ME",
	148: "MF",
	149: "MG",
	150: "MH",
	151: "MK",
	152: "ML",
	153: "MM",
	154: "MN",
	155: "MO",
	156: "MP",
	157: "MQ",
	158: "MR",
	159: "MS",
	160: "MT",
	161: "MU",
	162: "MV",
	163: "MW",
	164: "MX",
	165: "MY",
	166: "MZ",
	167: "NA",
	168: "NC",
	169: "NE",
	170: "NF",
	171: "NG",
	172: "NI",
	173: "NL",
	174: "NO",
	175: "NP",
	176: "NR",
	177: "NU",
	178: "NZ",
	179: "OM",
	180: "PA",
	181: "PE",
	182: "PF",
	183: "PG",
	184: "PH",
	185: "PK",
	186: "PL",
	187: "PM",
	188: "PN",
	189: "PR",
	190: "PS",
	191: "PT",
	192: "PW",
	193: "PY",
	194: "QA",
	195: "RE",
	196: "RO",
	197: "RS",
	198: "RU",
	199: "RW",
	200: "SA",
	201: "SB",
	202: "SC",
	203: "SD",
	204: "SE",
	205: "SG",
	206: "SH",
	207: "SI",
	208: "SJ",
	209: "SK",
	210: "SL",
	211: "SM",
	212: "SN",
	213: "SO",
	214: "SR",
	215: "SS",
	216: "ST",
	217: "SU",
	218: "SV",
	219: "SX",
	220: "SY",
	221: "SZ",
	222: "TC",
	223: "TD",
	224: "TF",
	225: "TG",
	226: "TH",
	227: "TJ",
	228: "TK",
	229: "TL",
	230: "TM",
	231: "TN",
	232: "TO",
	233: "TR",
	234: "TT",
	235: "TV",
	236: "TW",
	237: "TZ",
	238: "UA",
	239: "UG",
	240: "UM",
	241: "US",
	242: "UY",
	243: "UZ",
	244: "VA",
	245: "VC",
	246: "VD",
	247: "VE",
	248: "VG",
	249: "VI",
	250: "VN",
	251: "VU",
	252: "WF",
	253: "WS",
	254: "XK",
	255: "XP",
	256: "XR",
	257: "XS",
	258: "XT",
	259: "XU",
	260: "XV",
	261: "XW",
	262: "XY",
	263: "XZ",
	264: "YD",
	265: "YE",
	266: "YT",
	267: "YU",
	268: "ZA",
	269: "ZM",
	270: "ZW",
}
var Country_value = map[string]int32{
	"UNKNOWN_COUNTRY": 0,
	"SUPRANATIONAL":   1,
	"NOT_APPLICABLE":  2,
	"AD":              3,
	"AE":              4,
	"AF":              5,
	"AG":              6,
	"AI":              7,
	"AL":              8,
	"AM":              9,
	"AN":              10,
	"AO":              11,
	"AP":              12,
	"AQ":              13,
	"AR":              14,
	"AS":              15,
	"AT":              16,
	"AU":              17,
	"AW":              18,
	"AX":              19,
	"AZ":              20,
	"BA":              21,
	"BB":              22,
	"BD":              23,
	"BE":              24,
	"BF":              25,
	"BG":              26,
	"BH":              27,
	"BI":              28,
	"BJ":              29,
	"BL":              30,
	"BM":              31,
	"BN":              32,
	"BO":              33,
	"BQ":              34,
	"BR":              35,
	"BS":              36,
	"BT":              37,
	"BV":              38,
	"BW":              39,
	"BY":              40,
	"BZ":              41,
	"CA":              42,
	"CC":              43,
	"CD":              44,
	"CF":              45,
	"CG":              46,
	"CH":              47,
	"CI":              48,
	"CK":              49,
	"CL":              50,
	"CM":              51,
	"CN":              52,
	"CO":              53,
	"CR":              54,
	"CS":              55,
	"CU":              56,
	"CV":              57,
	"CW":              58,
	"CX":              59,
	"CY":              60,
	"CZ":              61,
	"DD":              62,
	"DE":              63,
	"DJ":              64,
	"DK":              65,
	"DM":              66,
	"DO":              67,
	"DZ":              68,
	"EC":              69,
	"EE":              70,
	"EG":              71,
	"EH":              72,
	"ER":              73,
	"ES":              74,
	"ET":              75,
	"EU":              76,
	"FI":              77,
	"FJ":              78,
	"FK":              79,
	"FM":              80,
	"FO":              81,
	"FR":              82,
	"GA":              83,
	"GB":              84,
	"GD":              85,
	"GE":              86,
	"GF":              87,
	"GG":              88,
	"GH":              89,
	"GI":              90,
	"GL":              91,
	"GM":              92,
	"GN":              93,
	"GP":              94,
	"GQ":              95,
	"GR":              96,
	"GS":              97,
	"GT":              98,
	"GU":              99,
	"GW":              100,
	"GY":              101,
	"HK":              102,
	"HM":              103,
	"HN":              104,
	"HR":              105,
	"HT":              106,
	"HU":              107,
	"ID":              108,
	"IE":              109,
	"IL":              110,
	"IM":              111,
	"IN":              112,
	"IO":              113,
	"IQ":              114,
	"IR":              115,
	"IS":              116,
	"IT":              117,
	"JE":              118,
	"JM":              119,
	"JO":              120,
	"JP":              121,
	"KE":              122,
	"KG":              123,
	"KH":              124,
	"KI":              125,
	"KM":              126,
	"KN":              127,
	"KP":              128,
	"KR":              129,
	"KW":              130,
	"KY":              131,
	"KZ":              132,
	"LA":              133,
	"LB":              134,
	"LC":              135,
	"LI":              136,
	"LK":              137,
	"LR":              138,
	"LS":              139,
	"LT":              140,
	"LU":              141,
	"LV":              142,
	"LY":              143,
	"MA":              144,
	"MC":              145,
	"MD":              146,
	"ME":              147,
	"MF":              148,
	"MG":              149,
	"MH":              150,
	"MK":              151,
	"ML":              152,
	"MM":              153,
	"MN":              154,
	"MO":              155,
	"MP":              156,
	"MQ":              157,
	"MR":              158,
	"MS":              159,
	"MT":              160,
	"MU":              161,
	"MV":              162,
	"MW":              163,
	"MX":              164,
	"MY":              165,
	"MZ":              166,
	"NA":              167,
	"NC":              168,
	"NE":              169,
	"NF":              170,
	"NG":              171,
	"NI":              172,
	"NL":              173,
	"NO":              174,
	"NP":              175,
	"NR":              176,
	"NU":              177,
	"NZ":              178,
	"OM":              179,
	"PA":              180,
	"PE":              181,
	"PF":              182,
	"PG":              183,
	"PH":              184,
	"PK":              185,
	"PL":              186,
	"PM":              187,
	"PN":              188,
	"PR":              189,
	"PS":              190,
	"PT":              191,
	"PW":              192,
	"PY":              193,
	"QA":              194,
	"RE":              195,
	"RO":              196,
	"RS":              197,
	"RU":              198,
	"RW":              199,
	"SA":              200,
	"SB":              201,
	"SC":              202,
	"SD":              203,
	"SE":              204,
	"SG":              205,
	"SH":              206,
	"SI":              207,
	"SJ":              208,
	"SK":              209,
	"SL":              210,
	"SM":              211,
	"SN":              212,
	"SO":              213,
	"SR":              214,
	"SS":              215,
	"ST":              216,
	"SU":              217,
	"SV":              218,
	"SX":              219,
	"SY":              220,
	"SZ":              221,
	"TC":              222,
	"TD":              223,
	"TF":              224,
	"TG":              225,
	"TH":              226,
	"TJ":              227,
	"TK":              228,
	"TL":              229,
	"TM":              230,
	"TN":              231,
	"TO":              232,
	"TR":              233,
	"TT":              234,
	"TV":              235,
	"TW":              236,
	"TZ":              237,
	"UA":              238,
	"UG":              239,
	"UM":              240,
	"US":              241,
	"UY":              242,
	"UZ":              243,
	"VA":              244,
	"VC":              245,
	"VD":              246,
	"VE":              247,
	"VG":              248,
	"VI":              249,
	"VN":              250,
	"VU":              251,
	"WF":              252,
	"WS":              253,
	"XK":              254,
	"XP":              255,
	"XR":              256,
	"XS":              257,
	"XT":              258,
	"XU":              259,
	"XV":              260,
	"XW":              261,
	"XY":              262,
	"XZ":              263,
	"YD":              264,
	"YE":              265,
	"YT":              266,
	"YU":              267,
	"ZA":              268,
	"ZM":              269,
	"ZW":              270,
}

func (x Country) String() string {
	return proto.EnumName(Country_name, int32(x))
}
func (Country) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_country_d8ce9fe065664f2f, []int{0}
}

func init() {
	proto.RegisterEnum("iso.protobuf.Country", Country_name, Country_value)
}

func init() { proto.RegisterFile("country.proto", fileDescriptor_country_d8ce9fe065664f2f) }

var fileDescriptor_country_d8ce9fe065664f2f = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0xd6, 0xf5, 0x7b, 0x5b, 0x87,
	0x1d, 0x85, 0xf1, 0xc5, 0xdb, 0x92, 0x4d, 0x0b, 0xbc, 0x51, 0x06, 0x59, 0xc6, 0xbc, 0x65, 0x5b,
	0xb2, 0x35, 0x65, 0xbe, 0x92, 0xae, 0xc0, 0xd2, 0xbd, 0x57, 0xbe, 0x20, 0x59, 0x2a, 0xa4, 0xb5,
	0x1b, 0x70, 0xd3, 0x58, 0x69, 0x62, 0xb7, 0x75, 0x31, 0xcc, 0x49, 0x99, 0x99, 0x99, 0x53, 0x66,
	0x66, 0x66, 0x66, 0x66, 0x66, 0x78, 0x74, 0xbe, 0x3f, 0xbd, 0x9f, 0xe7, 0x39, 0xff, 0xc0, 0x49,
	0x8d, 0xea, 0x6d, 0x0d, 0xf6, 0x0f, 0xcc, 0x1d, 0x9a, 0x34, 0x67, 0x6e, 0x6b, 0xa0, 0x95, 0x1e,
	0xd9, 0x37, 0xaf, 0x65, 0xec, 0x19, 0x9c, 0x3e, 0x71, 0x5d, 0x3a, 0x35, 0x22, 0x6b, 0x7b, 0x7a,
	0x5c, 0x6a, 0x4c, 0xe2, 0x97, 0xfd, 0xa0, 0xee, 0x4f, 0xcd, 0x06, 0x89, 0x1f, 0x87, 0x0d, 0x7e,
	0x90, 0x1e, 0x9b, 0x1a, 0x15, 0x25, 0xd5, 0xd0, 0xf1, 0x9d, 0xb8, 0x14, 0xf8, 0x4e, 0x85, 0x61,
	0xe9, 0x74, 0x6a, 0xb4, 0x1f, 0xc4, 0x53, 0x9d, 0x6a, 0xb5, 0x52, 0xca, 0x3a, 0x99, 0x8a, 0x4b,
	0x47, 0x7a, 0x78, 0xaa, 0xc3, 0xc9, 0xf1, 0x43, 0xd5, 0xe5, 0x47, 0x6a, 0x9e, 0x1f, 0xab, 0x05,
	0x86, 0xab, 0x25, 0x46, 0xa8, 0x15, 0x7e, 0xa2, 0x7a, 0xfc, 0x54, 0xf5, 0x49, 0xa9, 0x01, 0x3f,
	0x53, 0xab, 0x8c, 0x54, 0xbb, 0x18, 0xa5, 0x86, 0x8c, 0x56, 0x23, 0xc6, 0xa8, 0x31, 0xa8, 0x09,
	0x63, 0xd5, 0x3a, 0x69, 0xb5, 0x9b, 0x71, 0x6a, 0x93, 0x9f, 0xb7, 0x9b, 0x71, 0xf8, 0x85, 0x9a,
	0xe1, 0x97, 0x6a, 0x8e, 0x5f, 0xa9, 0x2e, 0xe3, 0xd5, 0x3c, 0xbf, 0x56, 0x0b, 0x4c, 0x50, 0x8b,
	0xfc, 0x46, 0x2d, 0xf1, 0x5b, 0xb5, 0x93, 0xdf, 0xa9, 0x15, 0x7e, 0xaf, 0x7a, 0xfc, 0x41, 0xf5,
	0xf9, 0xa3, 0x1a, 0xf0, 0x27, 0xb5, 0x8b, 0x3f, 0xab, 0x21, 0x7f, 0x51, 0x23, 0xfe, 0xaa, 0xc6,
	0xfc, 0x4d, 0xad, 0xf1, 0x77, 0xb5, 0xce, 0x3f, 0xd4, 0x06, 0xff, 0x54, 0x9b, 0xfc, 0xab, 0xdd,
	0xac, 0xc3, 0x44, 0x35, 0xcb, 0xbf, 0xd5, 0x1c, 0xff, 0x51, 0xf3, 0xfc, 0x57, 0x2d, 0x30, 0x49,
	0x2d, 0x32, 0x59, 0x2d, 0xf1, 0x3f, 0xb5, 0xcc, 0xff, 0xd5, 0x0a, 0xeb, 0xa9, 0x1e, 0x53, 0x54,
	0x9f, 0xf5, 0xd5, 0x80, 0x0d, 0xd4, 0x90, 0x0d, 0xd5, 0x88, 0x8d, 0xd4, 0x84, 0x8d, 0xd5, 0x1a,
	0x9b, 0xa8, 0x75, 0x36, 0x55, 0xbb, 0xd9, 0x4c, 0x6d, 0xb0, 0xb9, 0xda, 0x64, 0x8b, 0x76, 0x73,
	0x39, 0xb6, 0x54, 0x5d, 0xb6, 0x52, 0x3b, 0xd9, 0x5a, 0x2d, 0xe3, 0xa8, 0x1e, 0x19, 0x35, 0x20,
	0xab, 0x36, 0xc9, 0xb5, 0xeb, 0x66, 0x71, 0x55, 0x97, 0xbc, 0x5a, 0xa0, 0xa0, 0x16, 0x29, 0xaa,
	0x21, 0x25, 0x35, 0xa2, 0x53, 0x8d, 0x29, 0xab, 0x09, 0x95, 0x76, 0xf3, 0x25, 0x3c, 0xb5, 0x13,
	0x5f, 0x2d, 0x13, 0xa8, 0x1e, 0x55, 0x35, 0xa0, 0x4b, 0x0d, 0x09, 0xdb, 0x2d, 0x38, 0x44, 0x6a,
	0x86, 0x58, 0xcd, 0x91, 0xa8, 0x2e, 0x35, 0x35, 0x4f, 0x5d, 0x2d, 0xd0, 0xad, 0x16, 0x69, 0xa8,
	0x25, 0x9a, 0x6a, 0x85, 0x6d, 0x54, 0x8f, 0x6d, 0x55, 0x9f, 0xed, 0xd4, 0x2a, 0xdb, 0xab, 0x5d,
	0x4c, 0x55, 0x43, 0x76, 0x50, 0x23, 0x76, 0x54, 0x63, 0x7a, 0xd4, 0x84, 0x5e, 0xb5, 0xce, 0x4e,
	0x6a, 0x83, 0x69, 0xed, 0x16, 0xcb, 0x4c, 0x57, 0x3d, 0x66, 0xa8, 0x3e, 0x33, 0xd5, 0x90, 0x3e,
	0x35, 0x66, 0x67, 0x35, 0x61, 0x56, 0xbb, 0xa5, 0x1c, 0xbb, 0xa8, 0x2e, 0xb3, 0xd5, 0x0a, 0xfd,
	0xaa, 0x47, 0x4b, 0xf5, 0x99, 0xa3, 0x06, 0xec, 0xaa, 0x76, 0x31, 0x57, 0x0d, 0x99, 0xa7, 0x46,
	0x0c, 0xa8, 0x31, 0x83, 0xed, 0x76, 0xba, 0xec, 0xa6, 0x7a, 0xec, 0xae, 0x06, 0xec, 0xa1, 0x56,
	0x19, 0x6a, 0xb7, 0xec, 0xb2, 0xa7, 0x5a, 0x60, 0x2f, 0xb5, 0xc8, 0xde, 0x6a, 0x89, 0x7d, 0x54,
	0x8f, 0x7d, 0x55, 0x9f, 0xfd, 0xd2, 0x23, 0x52, 0x1d, 0xe5, 0x2a, 0xf3, 0x87, 0x09, 0x21, 0x0b,
	0x0c, 0x75, 0x16, 0x1a, 0x1a, 0x2c, 0x32, 0x34, 0x59, 0x2c, 0x54, 0x1c, 0x96, 0x18, 0x32, 0x2c,
	0x35, 0x64, 0x59, 0x66, 0x28, 0xb1, 0xdc, 0x50, 0x66, 0x85, 0x21, 0x64, 0xa5, 0x21, 0x62, 0x95,
	0x21, 0x66, 0xb5, 0x21, 0x61, 0x8d, 0xa1, 0xc6, 0x5a, 0x43, 0x83, 0xfd, 0x05, 0xcf, 0xe1, 0x00,
	0x43, 0x96, 0x03, 0x0d, 0x39, 0x0e, 0x32, 0xb8, 0x1c, 0x6c, 0xc8, 0x73, 0x88, 0xa1, 0xc0, 0xa1,
	0x86, 0x22, 0x87, 0x19, 0xca, 0x1c, 0x6e, 0xa8, 0x70, 0x84, 0xc1, 0xe3, 0x48, 0x83, 0xcf, 0x51,
	0x86, 0x80, 0xa3, 0x0d, 0x55, 0x8e, 0x31, 0x74, 0x71, 0xac, 0x21, 0xe4, 0x38, 0x43, 0xc4, 0xf1,
	0x86, 0x98, 0x13, 0x0c, 0x09, 0x27, 0x1a, 0x6a, 0x9c, 0x64, 0xa8, 0x73, 0xb2, 0xa1, 0x9b, 0x53,
	0x0c, 0x0d, 0x4e, 0x35, 0x34, 0x39, 0x4d, 0xf0, 0x1d, 0x4e, 0x37, 0x64, 0x39, 0xc3, 0xe0, 0x72,
	0xa6, 0x21, 0xcf, 0x59, 0x86, 0x02, 0x67, 0x1b, 0x4a, 0x9c, 0x63, 0xa8, 0x70, 0xae, 0x21, 0xe0,
	0x3c, 0x43, 0x95, 0xf3, 0x0d, 0x21, 0x17, 0x18, 0x12, 0x2e, 0x34, 0x34, 0xb9, 0x48, 0x08, 0x3c,
	0x2e, 0x16, 0xaa, 0x0e, 0xeb, 0x0c, 0x2e, 0x97, 0x18, 0xf2, 0x5c, 0x6a, 0x28, 0x70, 0x99, 0xa1,
	0xc8, 0xe5, 0x86, 0x32, 0x57, 0x18, 0x2a, 0x5c, 0x69, 0xf0, 0xb8, 0xca, 0xe0, 0x73, 0xb5, 0x21,
	0xe4, 0x1a, 0x43, 0xc4, 0xb5, 0x86, 0x98, 0xeb, 0x0c, 0x75, 0xae, 0x37, 0x34, 0xb8, 0x41, 0xe8,
	0x72, 0xb8, 0x51, 0x08, 0x5d, 0x6e, 0x32, 0x04, 0xdc, 0x6c, 0x88, 0xb8, 0xc5, 0x90, 0x70, 0xab,
	0xa1, 0xce, 0x6d, 0x42, 0xe4, 0x70, 0xbb, 0x21, 0xc3, 0x1d, 0x86, 0x2c, 0x77, 0x1a, 0x72, 0xdc,
	0x65, 0x70, 0xb9, 0xdb, 0x50, 0xe0, 0x1e, 0x43, 0x91, 0x7b, 0x0d, 0x25, 0xee, 0x33, 0x74, 0x72,
	0xbf, 0xa1, 0xcc, 0x03, 0x86, 0x0a, 0x0f, 0x1a, 0x3c, 0x1e, 0x32, 0xf8, 0x3c, 0x6c, 0x08, 0x78,
	0xc4, 0x10, 0xf2, 0xa8, 0x21, 0xe2, 0x31, 0x43, 0xcc, 0xe3, 0x86, 0x84, 0x27, 0x0c, 0x35, 0x9e,
	0x34, 0x74, 0xf3, 0x94, 0xa1, 0xc1, 0xd3, 0x86, 0x26, 0xcf, 0x08, 0x71, 0x96, 0x67, 0x0d, 0x39,
	0x9e, 0x33, 0xe4, 0x79, 0xde, 0x50, 0xe0, 0x05, 0x43, 0x91, 0x17, 0x0d, 0x9d, 0xbc, 0x64, 0x28,
	0xf3, 0xb2, 0xa1, 0xc2, 0x2b, 0x06, 0x8f, 0x57, 0x0d, 0x3e, 0xaf, 0x19, 0x02, 0x5e, 0x37, 0x84,
	0xbc, 0x61, 0x88, 0x79, 0xd3, 0x50, 0xe3, 0x2d, 0x43, 0x9d, 0xb7, 0x0d, 0x4d, 0xde, 0x11, 0x12,
	0x87, 0x77, 0x0d, 0x05, 0xde, 0x33, 0x78, 0xbc, 0x6f, 0x88, 0xf8, 0xc0, 0xd0, 0xe0, 0x43, 0x43,
	0x93, 0x8f, 0x84, 0x9a, 0xc3, 0xc7, 0x86, 0x2c, 0x9f, 0x18, 0x72, 0x7c, 0x6a, 0x70, 0xf9, 0xcc,
	0x50, 0xe0, 0x73, 0x43, 0x89, 0x2f, 0x0c, 0x3e, 0x5f, 0x1a, 0x12, 0xbe, 0x12, 0xea, 0x79, 0xbe,
	0x36, 0x44, 0x7c, 0x23, 0x74, 0x97, 0xf9, 0xd6, 0x50, 0xe5, 0x3b, 0x43, 0xc8, 0xfc, 0x0e, 0x21,
	0x62, 0x81, 0x21, 0x66, 0xa1, 0x21, 0x61, 0x91, 0xa1, 0xc6, 0x62, 0x43, 0x9d, 0x25, 0x86, 0x06,
	0x4b, 0x0d, 0x4d, 0x96, 0x09, 0x8d, 0x1c, 0xcb, 0x0d, 0x2e, 0x2b, 0x0c, 0x31, 0x2b, 0x0d, 0x09,
	0xab, 0x84, 0xa6, 0xc3, 0x6a, 0x83, 0xc7, 0x1a, 0x43, 0x9d, 0xb5, 0x1d, 0x99, 0x09, 0xcd, 0xf1,
	0x33, 0xfa, 0x06, 0x66, 0x0e, 0xf6, 0x4c, 0xea, 0x6d, 0xcd, 0x9e, 0xdc, 0x3f, 0xd4, 0x3b, 0xbb,
	0xd5, 0x3f, 0x6b, 0xda, 0xd0, 0xe4, 0xbe, 0x79, 0xad, 0x9e, 0xe1, 0x3a, 0x57, 0x53, 0xbe, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0x89, 0xdb, 0x82, 0x78, 0x09, 0x00, 0x00,
}
