// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: currency.proto

package iso // import "github.com/nycmonkey/iso"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strconv "strconv"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Currency int32

const (
	// N/A (active)
	UNKNOWN_CURRENCY Currency = 0
	// Andorran Peseta (inactive)
	ADP Currency = 1
	// Andorran Franc (inactive)
	ADR Currency = 2
	// U.A.E. Dirham (active)
	AED Currency = 3
	// Afghan Afghani (inactive)
	AFA Currency = 4
	// Afghan Afghani (active)
	AFN Currency = 5
	// Albanian Old Lek (inactive)
	ALK Currency = 6
	// Albanian Lek (active)
	ALL Currency = 7
	// Armenian Dram (active)
	AMD Currency = 8
	// Netherlands Antillean Guilder (active)
	ANG Currency = 9
	// Angolan Kwanza (active)
	AOA Currency = 10
	// Angolan New Kwanza (inactive)
	AON Currency = 11
	// Angolan Kwanza (inactive)
	AOR Currency = 12
	// Argentine Austral (inactive)
	ARA Currency = 13
	// Argentine Peso Ley (inactive)
	ARL Currency = 14
	// Argentine Peso Moneda Nacional (inactive)
	ARM Currency = 15
	// Argentine Peso Argentino (inactive)
	ARP Currency = 16
	// Argentine Peso (active)
	ARS Currency = 17
	// Austrian Schilling (inactive)
	ATS Currency = 18
	// Australian Dollar (active)
	AUD Currency = 19
	// Aruban Guilder (active)
	AWG Currency = 20
	// Azerbaijanian Manat (inactive)
	AZM Currency = 21
	// Azerbaijanian New Manat (active)
	AZN Currency = 22
	// Bosnian Marka (active)
	BAM Currency = 23
	// Barbados Dollar (active)
	BBD Currency = 24
	// Bangladeshi Taka (active)
	BDT Currency = 25
	// Belgian Franc (inactive)
	BEF Currency = 26
	// Bulgarian Lev (inactive)
	BGJ Currency = 27
	// Bulgarian Lev (inactive)
	BGK Currency = 28
	// Bulgarian Lev (inactive)
	BGL Currency = 29
	// Bulgarian Lev (active)
	BGN Currency = 30
	// Bahraini Dinar (active)
	BHD Currency = 31
	// Burundian Franc (active)
	BIF Currency = 32
	// Bermudian Dollar (active)
	BMD Currency = 33
	// Brunei Dollar (active)
	BND Currency = 34
	// Bolivian Boliviano (active)
	BOB Currency = 35
	// Bolivian Peso (inactive)
	BOP Currency = 36
	// Bolivian Mvdol (funds code) (active)
	BOV Currency = 37
	// Brazilian Cruzeiro Novo (inactive)
	BRB Currency = 38
	// Brazilian Cruzado (inactive)
	BRC Currency = 39
	// Brazilian Cruzeiro (inactive)
	BRE Currency = 40
	// Brazilian Real (active)
	BRL Currency = 41
	// Brazilian Cruzado Novo (inactive)
	BRN Currency = 42
	// Brazilian Cruzeiro Real (inactive)
	BRR Currency = 43
	// Brazilian Cruzeiro (inactive)
	BRZ Currency = 44
	// Bahamian Dollar (active)
	BSD Currency = 45
	// Bhutan Ngultrum (active)
	BTN Currency = 46
	// Botswana Pula (active)
	BWP Currency = 47
	// Belarus Ruble (inactive)
	BYB Currency = 48
	// Belarus Ruble (active)
	BYN Currency = 49
	// Belarus Ruble (inactive)
	BYR Currency = 50
	// Belize Dollar (active)
	BZD Currency = 51
	// Canadian Dollar (active)
	CAD Currency = 52
	// Congolese Franc (active)
	CDF Currency = 53
	// Swiss Franc (active)
	CHF Currency = 54
	// Chilean Escudo (inactive)
	CLE Currency = 55
	// Chilean Unidad de Fomento (active)
	CLF Currency = 56
	// Chilean Peso (active)
	CLP Currency = 57
	// Chinese Yuan Renminbi (HK) (active)
	CNH Currency = 58
	// Chinese Yuan Renminbi (active)
	CNY Currency = 59
	// Colombian Peso (active)
	COP Currency = 60
	// Colombian Unidad de Valor Real (active)
	COU Currency = 61
	// Costa Rican Colon (active)
	CRC Currency = 62
	// Serbian Dinar (inactive)
	CSD Currency = 63
	// Czechoslovak Koruna (inactive)
	CSK Currency = 64
	// Cuban Convertible Peso (active)
	CUC Currency = 65
	// Cuban Peso (active)
	CUP Currency = 66
	// Cape Verdean Escudo (active)
	CVE Currency = 67
	// Cypriot Pound (inactive)
	CYP Currency = 68
	// Czech Koruna (active)
	CZK Currency = 69
	// East German Mark (inactive)
	DDM Currency = 70
	// German Deutsche Mark (inactive)
	DEM Currency = 71
	// Djibouti Franc (active)
	DJF Currency = 72
	// Danish Krone (active)
	DKK Currency = 73
	// Dominican Peso (active)
	DOP Currency = 74
	// Algerian Dinar (active)
	DZD Currency = 75
	// Ecuadoran Sucre (inactive)
	ECS Currency = 76
	// Ecuadoran Unidad de Valor Constante (inactive)
	ECV Currency = 77
	// Estonian Kroon (inactive)
	EEK Currency = 78
	// Egyptian Pound (active)
	EGP Currency = 79
	// Eritrean Nakfa (active)
	ERN Currency = 80
	// Spanish Peseta (inactive)
	ESP Currency = 81
	// Ethopian Birr (active)
	ETB Currency = 82
	// Euro (active)
	EUR Currency = 83
	// Finnish Markka (inactive)
	FIM Currency = 84
	// Fiji Dollar (active)
	FJD Currency = 85
	// Falkland Islands Pound (active)
	FKP Currency = 86
	// French Franc (inactive)
	FRF Currency = 87
	// British Pound (active)
	GBP Currency = 88
	// British Pound (Pence) (active)
	GBX Currency = 89
	// Georgian Lari (inactive)
	GEK Currency = 90
	// Georgian Lari (active)
	GEL Currency = 91
	// Ghanaian Cedi (inactive)
	GHC Currency = 92
	// Ghanaian Cedi (active)
	GHS Currency = 93
	// Gibraltar Pound (active)
	GIP Currency = 94
	// Gambian Daasi (active)
	GMD Currency = 95
	// Guinean Syli (inactive)
	GNE Currency = 96
	// Guinea Franc (active)
	GNF Currency = 97
	// Equatorial Guinean Ekwele (inactive)
	GQE Currency = 98
	// Greek Drachma (inactive)
	GRD Currency = 99
	// Guatemalan Quetzal (active)
	GTQ Currency = 100
	// Guinea-Bissau Peso (inactive)
	GWP Currency = 101
	// Guyanan Dollar (active)
	GYD Currency = 102
	// Hong Kong Dollar (active)
	HKD Currency = 103
	// Honduran Lempira (active)
	HNL Currency = 104
	// Croatian Kuna (active)
	HRK Currency = 105
	// Haitian Gourde (active)
	HTG Currency = 106
	// Hungarian Forint (active)
	HUF Currency = 107
	// Indonesian Rupiah (active)
	IDR Currency = 108
	// Irish Pound (inactive)
	IEP Currency = 109
	// Israeli Lira (inactive)
	ILP Currency = 110
	// Israeli Shekel (inactive)
	ILR Currency = 111
	// Israeli New Shekel (active)
	ILS Currency = 112
	// Israeli Agora (active)
	ILX Currency = 113
	// Indian Rupee (active)
	INR Currency = 114
	// Iraqi Dinar (active)
	IQD Currency = 115
	// Iranian Rial (active)
	IRR Currency = 116
	// Icelandic Old Krona (inactive)
	ISJ Currency = 117
	// Icelandic Krona (active)
	ISK Currency = 118
	// Italian Lira (inactive)
	ITL Currency = 119
	// Jamaican Dollar (active)
	JMD Currency = 120
	// Jordanian Dinar (active)
	JOD Currency = 121
	// Japanese Yen (active)
	JPY Currency = 122
	// Kenyan Shilling (active)
	KES Currency = 123
	// Kyrgyzstan Som (active)
	KGS Currency = 124
	// Cambodian Riel (active)
	KHR Currency = 125
	// Comoros Franc (active)
	KMF Currency = 126
	// North Korean Won (active)
	KPW Currency = 127
	// Korean Won (active)
	KRW Currency = 128
	// Kuwaiti Dinar (active)
	KWD Currency = 129
	// Caymanian Dollar (active)
	KYD Currency = 130
	// Kazakhstan Tenge (active)
	KZT Currency = 131
	// Lao Kip (inactive)
	LAJ Currency = 132
	// Lao Kip (active)
	LAK Currency = 133
	// Lebanese Pound (active)
	LBP Currency = 134
	// Sri Lankan Rupee (active)
	LKR Currency = 135
	// Liberian Dollar (active)
	LRD Currency = 136
	// Lesotho Loti (active)
	LSL Currency = 137
	// Lithuanian Litas (inactive)
	LTL Currency = 138
	// Luxembourg Franc (inactive)
	LUF Currency = 139
	// Latvian Lat (inactive)
	LVL Currency = 140
	// Libyan Dinar (active)
	LYD Currency = 141
	// Moroccan Dirham (active)
	MAD Currency = 142
	// Moroccan Franc (inactive)
	MAF Currency = 143
	// Monegasque Franc (inactive)
	MCL Currency = 144
	// Moldova Leu (active)
	MDL Currency = 145
	// Malagasy Ariary (active)
	MGA Currency = 146
	// Malagasy Franc (inactive)
	MGF Currency = 147
	// Macedonian Denar (active)
	MKD Currency = 148
	// Old Macedonian Denar (inactive)
	MKN Currency = 149
	// Mali Franc (inactive)
	MLF Currency = 150
	// Myanmar Kyats (active)
	MMK Currency = 151
	// Mongolia Togrog (active)
	MNT Currency = 152
	// Macau Pataca (active)
	MOP Currency = 153
	// Mauritanian Ouguiya (active)
	MRO Currency = 154
	// Maltese Lira (inactive)
	MTL Currency = 155
	// Maltese Pound (inactive)
	MTP Currency = 156
	// Mauritius Rupee (active)
	MUR Currency = 157
	// Maldive Rupee (inactive)
	MVQ Currency = 158
	// Maldive Rufiyaa (active)
	MVR Currency = 159
	// Malawi Kwacha (active)
	MWK Currency = 160
	// Mexican Peso (active)
	MXN Currency = 161
	// Mexican Peso (inactive)
	MXP Currency = 162
	// Mexican Unidad de Inversion (UDI) (active)
	MXV Currency = 163
	// Malaysian Ringgit (active)
	MYR Currency = 164
	// Mozambican Metical (inactive)
	MZM Currency = 165
	// Mozambican Metical (active)
	MZN Currency = 166
	// Namibian Dollar (active)
	NAD Currency = 167
	// Newfoundland Dollar (inactive)
	NFD Currency = 168
	// Nigerian Naira (active)
	NGN Currency = 169
	// Nicaraguan Cordoba Oro (active)
	NIO Currency = 170
	// Dutch Guilder (inactive)
	NLG Currency = 171
	// Norwegian Krone (active)
	NOK Currency = 172
	// Nepalese Rupee (active)
	NPR Currency = 173
	// New Zealand Dollar (active)
	NZD Currency = 174
	// Omani Rial (active)
	OMR Currency = 175
	// Panamanian Balboa (active)
	PAB Currency = 176
	// Peruvian Sol (inactive)
	PEH Currency = 177
	// Peruvian Inti (inactive)
	PEI Currency = 178
	// Peruvian Nuevo Sol (active)
	PEN Currency = 179
	// Papua New Guinea Kina (active)
	PGK Currency = 180
	// Philippine Peso (active)
	PHP Currency = 181
	// Pakistani Rupee (active)
	PKR Currency = 182
	// Polish Zloty (active)
	PLN Currency = 183
	// Polish Zloty (inactive)
	PLZ Currency = 184
	// Portuguese Escudo (inactive)
	PTE Currency = 185
	// Paraguay Guarini (active)
	PYG Currency = 186
	// Qatari Rial (active)
	QAR Currency = 187
	// Romanian Leu (inactive)
	ROK Currency = 188
	// Romanian Leu (inactive)
	ROL Currency = 189
	// Romanian Leu (active)
	RON Currency = 190
	// Serbian Dinar (active)
	RSD Currency = 191
	// Russian Ruble (active)
	RUB Currency = 192
	// Russian Ruble (inactive)
	RUR Currency = 193
	// Rwandan Franc (active)
	RWF Currency = 194
	// Saudi Arabian Riyal (active)
	SAR Currency = 195
	// Solomon Islands Dollar (active)
	SBD Currency = 196
	// Seychelle Rupee (active)
	SCR Currency = 197
	// Sudanese Dinar (inactive)
	SDD Currency = 198
	// Sudanese Pound (active)
	SDG Currency = 199
	// Swedish Krona (active)
	SEK Currency = 200
	// Singapore Dollar (active)
	SGD Currency = 201
	// Saint Helenian Pound (active)
	SHP Currency = 202
	// Slovenian Tolar (inactive)
	SIT Currency = 203
	// Slovakian Koruna (inactive)
	SKK Currency = 204
	// Sierra Leone Leone (active)
	SLL Currency = 205
	// San Marinese Lira (inactive)
	SML Currency = 206
	// Somali Shilling (active)
	SOS Currency = 207
	// Suriname Dollar (active)
	SRD Currency = 208
	// Suriname Guilder (inactive)
	SRG Currency = 209
	// South Sudanese Pound (active)
	SSP Currency = 210
	// Sao Tome and Principe Dobra (active)
	STD Currency = 211
	// Soviet Union Ruble (inactive)
	SUR Currency = 212
	// Salvadoran Colon (inactive)
	SVC Currency = 213
	// Syrian Pound (active)
	SYP Currency = 214
	// Swaziland Lilangeni (active)
	SZL Currency = 215
	// Thai Baht (active)
	THB Currency = 216
	// Tajikistani Ruble (inactive)
	TJR Currency = 217
	// Tajikistani Somoni (active)
	TJS Currency = 218
	// Turkmenistani Manat (inactive)
	TMM Currency = 219
	// Turkmenistani Manat (active)
	TMT Currency = 220
	// Tunisian Dinar (active)
	TND Currency = 221
	// Tongan Pa'anga (active)
	TOP Currency = 222
	// Portuguese Timorese Escudo (inactive)
	TPE Currency = 223
	// Turkish Lira (inactive)
	TRL Currency = 224
	// Turkish Lira (active)
	TRY Currency = 225
	// Trinidad and Tobago Dollar (active)
	TTD Currency = 226
	// Taiwan Dollar (active)
	TWD Currency = 227
	// Tanzanian Shilling (active)
	TZS Currency = 228
	// Ukrainian Hryvna (active)
	UAH Currency = 229
	// Ukrainian Karbovanets (inactive)
	UAK Currency = 230
	// Uganda Shilling (inactive)
	UGS Currency = 231
	// Uganda Shilling (active)
	UGX Currency = 232
	// U.S. Dollar (active)
	USD Currency = 233
	// Uruguay Peso en Unidades Indexadas (active)
	UYI Currency = 234
	// Uruguayan Old Peso (inactive)
	UYN Currency = 235
	// Uruguayan Peso (active)
	UYU Currency = 236
	// Uzbekistan Sum (active)
	UZS Currency = 237
	// Vatican Lira (inactive)
	VAL Currency = 238
	// Venezuelan Old Bolivar (inactive)
	VEB Currency = 239
	// Venezuelan Bolivar (active)
	VEF Currency = 240
	// Vietnamese Old Dong (inactive)
	VNC Currency = 241
	// Vietnamese Dong (active)
	VND Currency = 242
	// Vanuatu Vatu (active)
	VUV Currency = 243
	// Samoan Tala (active)
	WST Currency = 244
	// CFA Franc (BEAC) (active)
	XAF Currency = 245
	// Silver (ounces) (inactive)
	XAG Currency = 246
	// Gold (ounces) (inactive)
	XAU Currency = 247
	// East Caribbean Dollar (active)
	XCD Currency = 248
	// IMF Special Drawing Rts (inactive)
	XDR Currency = 249
	// European Currency Unit (inactive)
	XEU Currency = 250
	// Gold Franc (inactive)
	XFO Currency = 251
	// CFA Franc (BCEAO) (active)
	XOF Currency = 252
	// Palladium (ounces) (active)
	XPD Currency = 253
	// CFP Franc (active)
	XPF Currency = 254
	// Platinum (ounces) (active)
	XPT Currency = 255
	// South Yemeni Dinar (inactive)
	YDD Currency = 256
	// Yemeni Rial (active)
	YER Currency = 257
	// Yugoslav Dinar (inactive)
	YOU Currency = 258
	// Yugoslav Dinar (inactive)
	YUD Currency = 259
	// Yugoslav Dinar (inactive)
	YUG Currency = 260
	// Yugoslav Dinar (inactive)
	YUM Currency = 261
	// Yugoslav Dinar (inactive)
	YUN Currency = 262
	// Yugoslav Dinar (inactive)
	YUR Currency = 263
	// Yugoslav Dinar (inactive)
	YUS Currency = 264
	// South African Financial Rand (inactive)
	ZAL Currency = 265
	// South African Rand (active)
	ZAR Currency = 266
	// Zambian Kwacha (inactive)
	ZMK Currency = 267
	// Zambian New Kwacha (active)
	ZMW Currency = 268
	// Zairean Zaire (inactive)
	ZRN Currency = 269
	// Zairean Zaire (inactive)
	ZRZ Currency = 270
	// Rhodesian Dollar (inactive)
	ZWC Currency = 271
	// Zimbabwean Dollar (inactive)
	ZWD Currency = 272
	// Zimbabwean Dollar (active)
	ZWL Currency = 273
	// Zimbabwean Dollar (inactive)
	ZWN Currency = 274
	// Zimbabwean Dollar (inactive)
	ZWR Currency = 275
)

var Currency_name = map[int32]string{
	0:   "UNKNOWN_CURRENCY",
	1:   "ADP",
	2:   "ADR",
	3:   "AED",
	4:   "AFA",
	5:   "AFN",
	6:   "ALK",
	7:   "ALL",
	8:   "AMD",
	9:   "ANG",
	10:  "AOA",
	11:  "AON",
	12:  "AOR",
	13:  "ARA",
	14:  "ARL",
	15:  "ARM",
	16:  "ARP",
	17:  "ARS",
	18:  "ATS",
	19:  "AUD",
	20:  "AWG",
	21:  "AZM",
	22:  "AZN",
	23:  "BAM",
	24:  "BBD",
	25:  "BDT",
	26:  "BEF",
	27:  "BGJ",
	28:  "BGK",
	29:  "BGL",
	30:  "BGN",
	31:  "BHD",
	32:  "BIF",
	33:  "BMD",
	34:  "BND",
	35:  "BOB",
	36:  "BOP",
	37:  "BOV",
	38:  "BRB",
	39:  "BRC",
	40:  "BRE",
	41:  "BRL",
	42:  "BRN",
	43:  "BRR",
	44:  "BRZ",
	45:  "BSD",
	46:  "BTN",
	47:  "BWP",
	48:  "BYB",
	49:  "BYN",
	50:  "BYR",
	51:  "BZD",
	52:  "CAD",
	53:  "CDF",
	54:  "CHF",
	55:  "CLE",
	56:  "CLF",
	57:  "CLP",
	58:  "CNH",
	59:  "CNY",
	60:  "COP",
	61:  "COU",
	62:  "CRC",
	63:  "CSD",
	64:  "CSK",
	65:  "CUC",
	66:  "CUP",
	67:  "CVE",
	68:  "CYP",
	69:  "CZK",
	70:  "DDM",
	71:  "DEM",
	72:  "DJF",
	73:  "DKK",
	74:  "DOP",
	75:  "DZD",
	76:  "ECS",
	77:  "ECV",
	78:  "EEK",
	79:  "EGP",
	80:  "ERN",
	81:  "ESP",
	82:  "ETB",
	83:  "EUR",
	84:  "FIM",
	85:  "FJD",
	86:  "FKP",
	87:  "FRF",
	88:  "GBP",
	89:  "GBX",
	90:  "GEK",
	91:  "GEL",
	92:  "GHC",
	93:  "GHS",
	94:  "GIP",
	95:  "GMD",
	96:  "GNE",
	97:  "GNF",
	98:  "GQE",
	99:  "GRD",
	100: "GTQ",
	101: "GWP",
	102: "GYD",
	103: "HKD",
	104: "HNL",
	105: "HRK",
	106: "HTG",
	107: "HUF",
	108: "IDR",
	109: "IEP",
	110: "ILP",
	111: "ILR",
	112: "ILS",
	113: "ILX",
	114: "INR",
	115: "IQD",
	116: "IRR",
	117: "ISJ",
	118: "ISK",
	119: "ITL",
	120: "JMD",
	121: "JOD",
	122: "JPY",
	123: "KES",
	124: "KGS",
	125: "KHR",
	126: "KMF",
	127: "KPW",
	128: "KRW",
	129: "KWD",
	130: "KYD",
	131: "KZT",
	132: "LAJ",
	133: "LAK",
	134: "LBP",
	135: "LKR",
	136: "LRD",
	137: "LSL",
	138: "LTL",
	139: "LUF",
	140: "LVL",
	141: "LYD",
	142: "MAD",
	143: "MAF",
	144: "MCL",
	145: "MDL",
	146: "MGA",
	147: "MGF",
	148: "MKD",
	149: "MKN",
	150: "MLF",
	151: "MMK",
	152: "MNT",
	153: "MOP",
	154: "MRO",
	155: "MTL",
	156: "MTP",
	157: "MUR",
	158: "MVQ",
	159: "MVR",
	160: "MWK",
	161: "MXN",
	162: "MXP",
	163: "MXV",
	164: "MYR",
	165: "MZM",
	166: "MZN",
	167: "NAD",
	168: "NFD",
	169: "NGN",
	170: "NIO",
	171: "NLG",
	172: "NOK",
	173: "NPR",
	174: "NZD",
	175: "OMR",
	176: "PAB",
	177: "PEH",
	178: "PEI",
	179: "PEN",
	180: "PGK",
	181: "PHP",
	182: "PKR",
	183: "PLN",
	184: "PLZ",
	185: "PTE",
	186: "PYG",
	187: "QAR",
	188: "ROK",
	189: "ROL",
	190: "RON",
	191: "RSD",
	192: "RUB",
	193: "RUR",
	194: "RWF",
	195: "SAR",
	196: "SBD",
	197: "SCR",
	198: "SDD",
	199: "SDG",
	200: "SEK",
	201: "SGD",
	202: "SHP",
	203: "SIT",
	204: "SKK",
	205: "SLL",
	206: "SML",
	207: "SOS",
	208: "SRD",
	209: "SRG",
	210: "SSP",
	211: "STD",
	212: "SUR",
	213: "SVC",
	214: "SYP",
	215: "SZL",
	216: "THB",
	217: "TJR",
	218: "TJS",
	219: "TMM",
	220: "TMT",
	221: "TND",
	222: "TOP",
	223: "TPE",
	224: "TRL",
	225: "TRY",
	226: "TTD",
	227: "TWD",
	228: "TZS",
	229: "UAH",
	230: "UAK",
	231: "UGS",
	232: "UGX",
	233: "USD",
	234: "UYI",
	235: "UYN",
	236: "UYU",
	237: "UZS",
	238: "VAL",
	239: "VEB",
	240: "VEF",
	241: "VNC",
	242: "VND",
	243: "VUV",
	244: "WST",
	245: "XAF",
	246: "XAG",
	247: "XAU",
	248: "XCD",
	249: "XDR",
	250: "XEU",
	251: "XFO",
	252: "XOF",
	253: "XPD",
	254: "XPF",
	255: "XPT",
	256: "YDD",
	257: "YER",
	258: "YOU",
	259: "YUD",
	260: "YUG",
	261: "YUM",
	262: "YUN",
	263: "YUR",
	264: "YUS",
	265: "ZAL",
	266: "ZAR",
	267: "ZMK",
	268: "ZMW",
	269: "ZRN",
	270: "ZRZ",
	271: "ZWC",
	272: "ZWD",
	273: "ZWL",
	274: "ZWN",
	275: "ZWR",
}
var Currency_value = map[string]int32{
	"UNKNOWN_CURRENCY": 0,
	"ADP":              1,
	"ADR":              2,
	"AED":              3,
	"AFA":              4,
	"AFN":              5,
	"ALK":              6,
	"ALL":              7,
	"AMD":              8,
	"ANG":              9,
	"AOA":              10,
	"AON":              11,
	"AOR":              12,
	"ARA":              13,
	"ARL":              14,
	"ARM":              15,
	"ARP":              16,
	"ARS":              17,
	"ATS":              18,
	"AUD":              19,
	"AWG":              20,
	"AZM":              21,
	"AZN":              22,
	"BAM":              23,
	"BBD":              24,
	"BDT":              25,
	"BEF":              26,
	"BGJ":              27,
	"BGK":              28,
	"BGL":              29,
	"BGN":              30,
	"BHD":              31,
	"BIF":              32,
	"BMD":              33,
	"BND":              34,
	"BOB":              35,
	"BOP":              36,
	"BOV":              37,
	"BRB":              38,
	"BRC":              39,
	"BRE":              40,
	"BRL":              41,
	"BRN":              42,
	"BRR":              43,
	"BRZ":              44,
	"BSD":              45,
	"BTN":              46,
	"BWP":              47,
	"BYB":              48,
	"BYN":              49,
	"BYR":              50,
	"BZD":              51,
	"CAD":              52,
	"CDF":              53,
	"CHF":              54,
	"CLE":              55,
	"CLF":              56,
	"CLP":              57,
	"CNH":              58,
	"CNY":              59,
	"COP":              60,
	"COU":              61,
	"CRC":              62,
	"CSD":              63,
	"CSK":              64,
	"CUC":              65,
	"CUP":              66,
	"CVE":              67,
	"CYP":              68,
	"CZK":              69,
	"DDM":              70,
	"DEM":              71,
	"DJF":              72,
	"DKK":              73,
	"DOP":              74,
	"DZD":              75,
	"ECS":              76,
	"ECV":              77,
	"EEK":              78,
	"EGP":              79,
	"ERN":              80,
	"ESP":              81,
	"ETB":              82,
	"EUR":              83,
	"FIM":              84,
	"FJD":              85,
	"FKP":              86,
	"FRF":              87,
	"GBP":              88,
	"GBX":              89,
	"GEK":              90,
	"GEL":              91,
	"GHC":              92,
	"GHS":              93,
	"GIP":              94,
	"GMD":              95,
	"GNE":              96,
	"GNF":              97,
	"GQE":              98,
	"GRD":              99,
	"GTQ":              100,
	"GWP":              101,
	"GYD":              102,
	"HKD":              103,
	"HNL":              104,
	"HRK":              105,
	"HTG":              106,
	"HUF":              107,
	"IDR":              108,
	"IEP":              109,
	"ILP":              110,
	"ILR":              111,
	"ILS":              112,
	"ILX":              113,
	"INR":              114,
	"IQD":              115,
	"IRR":              116,
	"ISJ":              117,
	"ISK":              118,
	"ITL":              119,
	"JMD":              120,
	"JOD":              121,
	"JPY":              122,
	"KES":              123,
	"KGS":              124,
	"KHR":              125,
	"KMF":              126,
	"KPW":              127,
	"KRW":              128,
	"KWD":              129,
	"KYD":              130,
	"KZT":              131,
	"LAJ":              132,
	"LAK":              133,
	"LBP":              134,
	"LKR":              135,
	"LRD":              136,
	"LSL":              137,
	"LTL":              138,
	"LUF":              139,
	"LVL":              140,
	"LYD":              141,
	"MAD":              142,
	"MAF":              143,
	"MCL":              144,
	"MDL":              145,
	"MGA":              146,
	"MGF":              147,
	"MKD":              148,
	"MKN":              149,
	"MLF":              150,
	"MMK":              151,
	"MNT":              152,
	"MOP":              153,
	"MRO":              154,
	"MTL":              155,
	"MTP":              156,
	"MUR":              157,
	"MVQ":              158,
	"MVR":              159,
	"MWK":              160,
	"MXN":              161,
	"MXP":              162,
	"MXV":              163,
	"MYR":              164,
	"MZM":              165,
	"MZN":              166,
	"NAD":              167,
	"NFD":              168,
	"NGN":              169,
	"NIO":              170,
	"NLG":              171,
	"NOK":              172,
	"NPR":              173,
	"NZD":              174,
	"OMR":              175,
	"PAB":              176,
	"PEH":              177,
	"PEI":              178,
	"PEN":              179,
	"PGK":              180,
	"PHP":              181,
	"PKR":              182,
	"PLN":              183,
	"PLZ":              184,
	"PTE":              185,
	"PYG":              186,
	"QAR":              187,
	"ROK":              188,
	"ROL":              189,
	"RON":              190,
	"RSD":              191,
	"RUB":              192,
	"RUR":              193,
	"RWF":              194,
	"SAR":              195,
	"SBD":              196,
	"SCR":              197,
	"SDD":              198,
	"SDG":              199,
	"SEK":              200,
	"SGD":              201,
	"SHP":              202,
	"SIT":              203,
	"SKK":              204,
	"SLL":              205,
	"SML":              206,
	"SOS":              207,
	"SRD":              208,
	"SRG":              209,
	"SSP":              210,
	"STD":              211,
	"SUR":              212,
	"SVC":              213,
	"SYP":              214,
	"SZL":              215,
	"THB":              216,
	"TJR":              217,
	"TJS":              218,
	"TMM":              219,
	"TMT":              220,
	"TND":              221,
	"TOP":              222,
	"TPE":              223,
	"TRL":              224,
	"TRY":              225,
	"TTD":              226,
	"TWD":              227,
	"TZS":              228,
	"UAH":              229,
	"UAK":              230,
	"UGS":              231,
	"UGX":              232,
	"USD":              233,
	"UYI":              234,
	"UYN":              235,
	"UYU":              236,
	"UZS":              237,
	"VAL":              238,
	"VEB":              239,
	"VEF":              240,
	"VNC":              241,
	"VND":              242,
	"VUV":              243,
	"WST":              244,
	"XAF":              245,
	"XAG":              246,
	"XAU":              247,
	"XCD":              248,
	"XDR":              249,
	"XEU":              250,
	"XFO":              251,
	"XOF":              252,
	"XPD":              253,
	"XPF":              254,
	"XPT":              255,
	"YDD":              256,
	"YER":              257,
	"YOU":              258,
	"YUD":              259,
	"YUG":              260,
	"YUM":              261,
	"YUN":              262,
	"YUR":              263,
	"YUS":              264,
	"ZAL":              265,
	"ZAR":              266,
	"ZMK":              267,
	"ZMW":              268,
	"ZRN":              269,
	"ZRZ":              270,
	"ZWC":              271,
	"ZWD":              272,
	"ZWL":              273,
	"ZWN":              274,
	"ZWR":              275,
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_currency_86fdf299d522e78d, []int{0}
}

func init() {
	proto.RegisterEnum("iso.protobuf.Currency", Currency_name, Currency_value)
}
func (x Currency) String() string {
	s, ok := Currency_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

func init() { proto.RegisterFile("currency.proto", fileDescriptor_currency_86fdf299d522e78d) }

var fileDescriptor_currency_86fdf299d522e78d = []byte{
	// 1282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xd6, 0x67, 0x9f, 0xdc, 0x56,
	0x19, 0x40, 0xf1, 0x1d, 0x1b, 0x12, 0xb3, 0x84, 0x70, 0x58, 0x0c, 0x84, 0x36, 0xf4, 0x16, 0xc0,
	0x06, 0x42, 0xef, 0x1a, 0x5d, 0x49, 0x33, 0x2b, 0xe9, 0xea, 0xee, 0x95, 0x34, 0xb3, 0x23, 0x4a,
	0xc0, 0x8b, 0x93, 0x98, 0x60, 0x6f, 0x70, 0x01, 0x4c, 0x75, 0x7a, 0x4f, 0x9c, 0x84, 0xde, 0x3b,
	0xa1, 0xf7, 0xde, 0x7b, 0xe8, 0xa6, 0x9b, 0x9a, 0x78, 0x4d, 0x09, 0xdd, 0xf4, 0x0e, 0xf9, 0xcd,
	0xf3, 0xdc, 0x77, 0xff, 0x17, 0xe7, 0x03, 0x9c, 0xf9, 0x63, 0x57, 0xf6, 0xec, 0xdc, 0xb9, 0x75,
	0xc7, 0xca, 0xde, 0x4d, 0xa7, 0xed, 0x5c, 0xdd, 0xbd, 0xba, 0x70, 0xcc, 0xb6, 0x5d, 0xab, 0xca,
	0x2d, 0x7b, 0x4e, 0x3a, 0xfe, 0xea, 0x8d, 0xf3, 0x1b, 0xe2, 0x10, 0x2c, 0x6c, 0x9c, 0xa7, 0xb5,
	0xb9, 0xad, 0x26, 0xf6, 0xc4, 0xb8, 0xf5, 0x3e, 0xb1, 0xf1, 0x94, 0xb9, 0x85, 0xa3, 0xe7, 0xd7,
	0x47, 0xc6, 0xd1, 0x53, 0x78, 0xd6, 0x09, 0x12, 0xc3, 0x7a, 0x41, 0x1a, 0x71, 0x3d, 0x85, 0xe5,
	0xfa, 0x82, 0x22, 0xe7, 0x28, 0x45, 0xc1, 0xd1, 0x82, 0xd2, 0xb0, 0x41, 0x60, 0x33, 0x6e, 0x20,
	0xa8, 0x22, 0xe6, 0x15, 0x96, 0x1b, 0x2a, 0x3c, 0xc7, 0x08, 0x7c, 0xc4, 0x8d, 0x14, 0x05, 0xc7,
	0x2a, 0x4a, 0x6e, 0xac, 0x70, 0xa0, 0xa8, 0xb9, 0x89, 0xa0, 0xa9, 0x59, 0x10, 0xb4, 0x86, 0x9b,
	0x0a, 0x26, 0x19, 0x1b, 0x05, 0x5d, 0xc9, 0xcd, 0x14, 0x96, 0x9b, 0xcf, 0x30, 0x88, 0x4a, 0x6e,
	0x21, 0x18, 0x18, 0x8e, 0x13, 0x98, 0x86, 0x5b, 0x0a, 0x92, 0x94, 0x5b, 0x09, 0xb2, 0x45, 0x6e,
	0xad, 0xc8, 0xb9, 0x8d, 0xa2, 0xe0, 0xb6, 0x0a, 0x4b, 0x5f, 0x30, 0x34, 0xdc, 0x4e, 0x30, 0x4a,
	0xb9, 0xbd, 0xa0, 0x34, 0xdc, 0x41, 0x60, 0x0d, 0x77, 0x14, 0x54, 0x03, 0xee, 0xa4, 0x70, 0xdc,
	0x59, 0x31, 0xe6, 0x2e, 0x02, 0x3f, 0xe0, 0xae, 0x8a, 0x98, 0xbb, 0x29, 0x12, 0xee, 0xae, 0x28,
	0xb8, 0x87, 0xc2, 0x72, 0xbc, 0xc2, 0x73, 0x4f, 0x45, 0xc7, 0xbd, 0x04, 0xb5, 0xe1, 0xde, 0x82,
	0xc6, 0xb2, 0x49, 0x30, 0x71, 0x6c, 0x16, 0x4c, 0x07, 0xdc, 0x47, 0x61, 0xb9, 0xaf, 0xc2, 0x73,
	0x3f, 0x41, 0x67, 0x38, 0x61, 0x86, 0x38, 0x32, 0xdc, 0x5f, 0x60, 0x52, 0x1e, 0x20, 0x18, 0xa6,
	0x3c, 0x50, 0x50, 0x24, 0x3c, 0x48, 0x91, 0xf2, 0x60, 0x85, 0xe3, 0x21, 0x02, 0x3b, 0xe4, 0xa1,
	0x8a, 0x29, 0x0f, 0x13, 0x54, 0x8e, 0x87, 0x2b, 0x5a, 0x1e, 0x21, 0xf0, 0x31, 0x8f, 0x14, 0xd4,
	0x86, 0x47, 0x29, 0x72, 0x1e, 0x2d, 0x68, 0x63, 0x22, 0x85, 0x63, 0x20, 0x18, 0x27, 0xc4, 0x82,
	0xa9, 0xc3, 0x08, 0xba, 0x9c, 0x64, 0x06, 0x63, 0x4a, 0x52, 0x41, 0x52, 0x92, 0x09, 0x16, 0x53,
	0x86, 0x82, 0x3c, 0x67, 0x24, 0xa8, 0x1c, 0x8b, 0x82, 0xce, 0x90, 0xcf, 0x90, 0xc4, 0x35, 0x85,
	0x62, 0x4c, 0x29, 0x48, 0x72, 0xac, 0x20, 0x73, 0x54, 0x02, 0x6f, 0x71, 0x82, 0xda, 0xb1, 0x24,
	0x68, 0x06, 0x78, 0x41, 0xeb, 0xa9, 0x67, 0x48, 0x47, 0x25, 0x8d, 0x60, 0xd1, 0xd0, 0x0a, 0x72,
	0xc7, 0x58, 0xe0, 0x53, 0x26, 0x33, 0x64, 0x03, 0xc7, 0xb2, 0x62, 0x99, 0xa9, 0x20, 0xc9, 0xe9,
	0x14, 0x05, 0x8f, 0x11, 0x0c, 0x63, 0x1e, 0xab, 0xa8, 0x79, 0x9c, 0x60, 0xe4, 0x78, 0xbc, 0xa0,
	0x34, 0x9c, 0x28, 0xb0, 0x09, 0x4f, 0x50, 0xa4, 0x3c, 0x51, 0xb0, 0x94, 0xb0, 0x45, 0xe0, 0x0d,
	0x2b, 0x82, 0x66, 0x89, 0x27, 0x09, 0x26, 0x8e, 0xad, 0x82, 0xa9, 0xe1, 0xa4, 0x19, 0x86, 0xb9,
	0xe1, 0x64, 0x81, 0x2d, 0x38, 0x45, 0xe0, 0x73, 0xb6, 0x09, 0x9a, 0x8c, 0x27, 0x0b, 0xda, 0x94,
	0x53, 0x67, 0x18, 0x19, 0xcf, 0x53, 0x04, 0x89, 0x63, 0xbb, 0xa0, 0x70, 0xec, 0x50, 0x78, 0x56,
	0x15, 0x35, 0xa7, 0x29, 0x96, 0x79, 0xaa, 0xc0, 0x7a, 0x76, 0x0a, 0x96, 0x0c, 0xbb, 0x04, 0xde,
	0xb3, 0x5b, 0x50, 0x2f, 0xb2, 0x47, 0x91, 0xf3, 0x34, 0x41, 0x53, 0xf0, 0xf4, 0x19, 0x16, 0x4b,
	0xc3, 0x33, 0x04, 0x95, 0x61, 0xaf, 0xc0, 0x4d, 0x79, 0xe6, 0x0c, 0x79, 0x52, 0xf3, 0x2c, 0x41,
	0x56, 0xf3, 0x6c, 0xc1, 0xd0, 0xf3, 0x1c, 0x41, 0x99, 0xf2, 0x5c, 0x81, 0x9b, 0xf0, 0xbc, 0x85,
	0x0d, 0xf3, 0xeb, 0x73, 0x3f, 0x61, 0x5f, 0x4f, 0x34, 0x31, 0x9c, 0xae, 0x9a, 0x1a, 0xce, 0x50,
	0x75, 0x0d, 0x67, 0x8a, 0x8a, 0x68, 0x91, 0xb3, 0x82, 0x72, 0xce, 0x56, 0x0d, 0x1c, 0xe7, 0xa8,
	0x72, 0xcf, 0xb9, 0x2a, 0x6f, 0x38, 0x4f, 0x55, 0x17, 0x9c, 0xaf, 0x6a, 0x0a, 0x2e, 0x50, 0xb5,
	0x29, 0x17, 0xaa, 0xc6, 0x05, 0x17, 0xa9, 0xa6, 0x86, 0x8b, 0x45, 0x65, 0x64, 0xb8, 0x24, 0x28,
	0xe5, 0x52, 0x55, 0x5c, 0xb0, 0x5f, 0x65, 0x0a, 0x2e, 0x53, 0x65, 0x11, 0x97, 0x07, 0xa5, 0x5c,
	0xa1, 0xca, 0x0d, 0xcf, 0x0f, 0xb2, 0xbc, 0x40, 0x55, 0xa4, 0xbc, 0x50, 0x55, 0xe6, 0xbc, 0x48,
	0x65, 0x1b, 0x5e, 0xac, 0xaa, 0x1c, 0x2f, 0x51, 0xf9, 0x8a, 0x97, 0xaa, 0x9a, 0x82, 0x97, 0x05,
	0x39, 0x5e, 0xae, 0x6a, 0x3d, 0xaf, 0x50, 0x8d, 0x97, 0x78, 0x65, 0x90, 0xe7, 0x55, 0xaa, 0x49,
	0xce, 0xab, 0x55, 0xcb, 0x96, 0xd7, 0x04, 0x39, 0x5e, 0x1b, 0x34, 0xe6, 0x75, 0xaa, 0xa9, 0xe7,
	0xf5, 0xaa, 0xae, 0xe4, 0x0d, 0x41, 0x96, 0x37, 0x8a, 0x6c, 0x64, 0x78, 0x93, 0x2a, 0x35, 0x5c,
	0xa9, 0xca, 0x2c, 0x6f, 0x56, 0x8d, 0x2a, 0xde, 0xa2, 0x2a, 0x32, 0xde, 0xaa, 0xaa, 0x72, 0xde,
	0xa6, 0x72, 0x9e, 0xb7, 0xab, 0x3a, 0xc3, 0x3b, 0x44, 0x55, 0xe9, 0x79, 0xa7, 0xc8, 0x45, 0x03,
	0xde, 0xa5, 0x4a, 0x86, 0xbc, 0x3b, 0x68, 0xc4, 0x7b, 0x82, 0x2c, 0xef, 0x55, 0x65, 0x39, 0xef,
	0x53, 0x0d, 0x1d, 0xef, 0x57, 0xe5, 0x9e, 0x0f, 0xa8, 0x0a, 0xcb, 0x07, 0x83, 0x3a, 0x3e, 0xa4,
	0x6a, 0x12, 0x3e, 0xac, 0x9a, 0x66, 0x7c, 0x44, 0xb4, 0x14, 0x79, 0x3e, 0x2a, 0xf2, 0x55, 0xce,
	0xc7, 0x82, 0x0a, 0x3e, 0x1e, 0x64, 0xf9, 0x84, 0xaa, 0x36, 0x7c, 0x52, 0xd5, 0x0e, 0xf8, 0x54,
	0x90, 0xe7, 0xd3, 0xaa, 0x49, 0xca, 0x67, 0x44, 0x75, 0xe4, 0xf9, 0xac, 0x6a, 0x60, 0xf8, 0x9c,
	0x2a, 0xf6, 0x7c, 0x5e, 0x65, 0x0c, 0x5f, 0x08, 0xca, 0xf8, 0xa2, 0x2a, 0xc9, 0xb9, 0x4a, 0x95,
	0x19, 0xbe, 0xa4, 0x1a, 0x3a, 0xbe, 0xac, 0x1a, 0x35, 0x7c, 0x45, 0x95, 0xe7, 0x7c, 0x55, 0x55,
	0x14, 0x7c, 0x4d, 0x55, 0x16, 0x7c, 0x5d, 0x55, 0xd5, 0x7c, 0x43, 0xe5, 0x0d, 0x07, 0x82, 0x32,
	0xbe, 0xa9, 0xaa, 0x1d, 0xdf, 0x52, 0x35, 0x86, 0x6f, 0xab, 0x5a, 0xcf, 0x77, 0x54, 0xe3, 0x98,
	0xef, 0xaa, 0xa6, 0x8e, 0xef, 0xa9, 0xba, 0x82, 0xef, 0x8b, 0x9a, 0xe1, 0x80, 0x83, 0xaa, 0x45,
	0xcf, 0x0f, 0x82, 0x6a, 0x7e, 0xa8, 0x2a, 0x4b, 0x7e, 0x14, 0xd4, 0xf0, 0x63, 0x95, 0x35, 0xfc,
	0x44, 0x55, 0x39, 0x7e, 0xaa, 0x72, 0x09, 0x57, 0xab, 0x7c, 0xc1, 0x35, 0x41, 0x53, 0x0e, 0xa9,
	0x1a, 0xc3, 0x9a, 0x6a, 0x62, 0x38, 0xac, 0xea, 0x6a, 0x7e, 0x26, 0x6a, 0xa3, 0x21, 0x3f, 0x0f,
	0xca, 0xf9, 0x85, 0x2a, 0xab, 0xf9, 0x65, 0xd0, 0x32, 0xd7, 0xaa, 0x6a, 0xc3, 0xaf, 0x54, 0xd3,
	0x11, 0xbf, 0x0e, 0xb2, 0xfc, 0x26, 0xa8, 0xe5, 0xb7, 0xaa, 0xae, 0xe6, 0x77, 0xa2, 0x71, 0x54,
	0xf0, 0x7b, 0x55, 0x32, 0xe0, 0x0f, 0x41, 0x29, 0x47, 0x54, 0x36, 0xe6, 0x8f, 0x41, 0x86, 0x3f,
	0xa9, 0xda, 0x31, 0x7f, 0x16, 0x4d, 0xea, 0x86, 0xbf, 0x88, 0x96, 0xa3, 0x94, 0xbf, 0x06, 0x65,
	0xfc, 0x2d, 0xa8, 0xe5, 0xef, 0xaa, 0xd8, 0xf0, 0x0f, 0x95, 0xf1, 0xfc, 0x53, 0x95, 0xb4, 0xfc,
	0x4b, 0x95, 0x56, 0xfc, 0x5b, 0x55, 0xa5, 0xfc, 0x47, 0xe5, 0x0c, 0xff, 0x0d, 0x4a, 0xf9, 0x5f,
	0x50, 0xc3, 0xff, 0x45, 0x53, 0x63, 0xd8, 0xb7, 0x4e, 0x94, 0x78, 0x4e, 0x57, 0x55, 0x2d, 0x67,
	0xa8, 0x5a, 0xc3, 0x99, 0x41, 0x19, 0x67, 0x05, 0x95, 0x9c, 0x1d, 0x64, 0x39, 0x27, 0xc8, 0x73,
	0x6e, 0x50, 0xcd, 0x79, 0xa2, 0x2e, 0x2a, 0x38, 0x3f, 0xc8, 0x73, 0x81, 0xaa, 0xcc, 0xb9, 0x30,
	0x68, 0xc2, 0x45, 0x2a, 0x6f, 0xb9, 0x38, 0xa8, 0xe3, 0x12, 0xd5, 0x24, 0xe6, 0xd2, 0x20, 0xc3,
	0xfe, 0xa0, 0x82, 0xcb, 0x82, 0x2c, 0x97, 0x07, 0x79, 0xae, 0x58, 0x37, 0xb0, 0x07, 0x0e, 0xf5,
	0xe7, 0x0e, 0x1e, 0xea, 0xcf, 0x1d, 0x39, 0xd4, 0xef, 0xed, 0x5b, 0xeb, 0xf7, 0xae, 0x5c, 0xeb,
	0xf7, 0xae, 0x5a, 0xeb, 0xf7, 0x0e, 0xac, 0xf5, 0x7b, 0xd7, 0xac, 0xf5, 0x7b, 0xd7, 0xae, 0xf5,
	0xe7, 0x8e, 0xac, 0xf5, 0x7b, 0xfb, 0x0f, 0xf7, 0xe7, 0x0e, 0x1c, 0xee, 0xcf, 0x1d, 0x3c, 0xdc,
	0x9f, 0xeb, 0x8e, 0x3b, 0x79, 0xdb, 0xee, 0x53, 0xf6, 0x6c, 0xd9, 0xb4, 0xb2, 0xba, 0x7d, 0xf3,
	0x8e, 0xbd, 0x2b, 0xdb, 0x57, 0x77, 0x9c, 0xba, 0x75, 0xef, 0xe6, 0x6d, 0xbb, 0x56, 0xb7, 0x1c,
	0x25, 0xef, 0x7a, 0xc2, 0x75, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x49, 0x10, 0x02, 0xd8, 0x0a,
	0x00, 0x00,
}
